version: '3.4'

services:
  chessonline.authorizationwebapplication:
    image: ${DOCKER_REGISTRY-}chessonlineauthorizationwebapplication
    build:
      context: .
      dockerfile: ChessOnline.AuthorizationWebApplication/Dockerfile
  chessonline.vuejsapp:
    image: chessonlinevuejsapp
    build:
        context: './chess-online-vue-js-app'
        dockerfile: Dockerfile
  proxy:
    image: nginx:mainline
